# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    book_images_directory: '%kernel.project_dir%/public/images/books'
    telegram_bot_token: '6105444296:AAHe1kNDtwCYjKAEo8UQEm9iSGkYwYeTt2I'
    telegram_chat_id: '908714473'
    websocket_port: 9502

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
#    app.form.type.product:
#        class: App\Form\ProductType
#        arguments: [ "@doctrine.orm.entity_manager" ]
#        tags:
#            - { name: form.type }

#    App\EventListener\TelegramNotificationListener:
#        arguments:
#            $httpClient: '@http_client'
#            $botToken: '%telegram_bot_token%'
#            $chatId: '%telegram_chat_id%'
#        tags:
#            - { name: kernel.event_listener, event: 'App\Event\NewBookEvent::NAME', method: 'onNewBook' }

#    App\Server\ChatWebSocketServer:
#        arguments: [ '@doctrine', '%websocket_port%' ]

